use_frameworks!

target 'RPHTTPServiceClient_Example' do
  pod 'RPHTTPServiceClient', :path => '../'
  pod 'Moya', '11.0.2'
  pod 'Moya-ObjectMapper', '2.7'
  pod 'ObjectMapper', '3.3'
  pod 'Alamofire', '4.7'


  target 'RPHTTPServiceClient_Tests' do
    inherit! :search_paths

  end
end
